### PR TITLE
Feature/58 unittests ci

### PR DESCRIPTION
**Pull request by zuevval**
Partially solved #58 

- moved some tests from `androidTest` to `test`, so they may be run without AVD
- fixed `gradlew` (https://stackoverflow.com/a/53943650)
- merged `dev`
- added bage to README: [Actions Status](https://github.com/braille-systems/learn-braille/actions) (of course it shows FAILING because reflects main repo CI status)

### CODE REVIEW

**Comment by winter-yuki** [comment]
I've merged `dev` into the `ci` branch. Can you please recreate PR to have proper diff?

**Comment by zuevval** [comment]
I've merged `ci` into this branch in turn, so the diff is proper now

**Comment by winter-yuki** [comment]
Very good job

**Comment by zuevval** [comment]
by the way, I have no idea why `diff` is proper in `_KotlinTest.kt` which I copied and pasted with `Ctrl+C -> Ctrl+V` and not so smart in other tests which I moved with AndroidStudio's drag-and-drop interface.

**Pull request merged**
