### PR TITLE
#327 remove octave marks

### LINKED ISSUE #327: wrong octave marks mapping
Alexei Viktorovich said that octave marks are wrong (according to Russian Braille notes)

TODO remove octave marks for now

### LINKED ISSUE #330: Bug: no `showMarkerPrintRules` for `musicHyphen`
image

Well, it's my fault.
This bug is in production. Deleting octave marks in a hurry on October 31st (#328), I've deleted the `inputMarkerPrintRules` for `musicHyphen`, which may cause Practice to crash.
CI failed, but I've released the app because there was no time to stop and think.

There were two crashes so far: the first is mine (I've done it intentionally) and the second from some user I do not know.

Now I must fix the bug and write a new database migration.
Probably this will come along with correct octave marks.

### PR DESCRIPTION
**Pull request by zuevval**

### CODE REVIEW

**Comment by zuevval** [comment]
we've changed octave marks mapping and are almost ready for a small update; I will try to upload AAB (instead of convenient APK) as a beta update, then test it and, if everything's nice, roll out the main update

**Comment by zuevval** [comment]
submitted for open testing

**Comment by zuevval** [comment]
Tested on my Samsung. Submitted the working version (currently under review). @winter-yuki please consider merging this PR.

**Review by penguin-boxx — APPROVED** [review]
It's hard for me to verify such PRs. But it looks good in general.

**Pull request merged**
