### PR TITLE
Feature/stats

### LINKED ISSUE #216: add "Statistics" section
When user clicks "statistics", he may see:
- number of times he opened Practice
- number of times he opened Theory
- number of cards he took in Practice (overall and correct)
- number of passed lessons and steps (overall and input steps)

### PR DESCRIPTION
**Pull request by winter-yuki**
Closes #216

### CODE REVIEW

**Comment by winter-yuki** [comment]
> > Finnish 216
> 
> What does it have to do with Finland I wonder slightly_smiling_face

Linus is blessing this PR

**Comment by zuevval** [comment]
remove this pic

**Comment by zuevval** [comment]
it violates github rules

**Comment by zuevval** [comment]
do you see the last option in the list? Beware it
image

**Comment by zuevval** [comment]
Update. Launched on a tablet over old version.

First time it crashed with the output https://pastebin.com/M0sw3u4j

From the second time on it works fine.

**Comment by zuevval** [comment]
I will examine it more thoroughly and I am going to test specifically if it crashes when installed over 1.0.0 or 1.0.2.

**Comment by zuevval** [comment]
NB: before merge I will update help message in the main menu

**Comment by zuevval** [comment]
Tomorrow I will read and test everything thoroughly, many thanks

**Comment by winter-yuki** [comment]
> @winter-yuki about UI: I like what I've seen on my tablet in "Statistics" menu (I really honestly truly like it, it will help me test hypotheses about the app usage), but:
> 
>     1. Should we really place that button in the main menu stack? Maybe in settings, or an icon in the main menu titlebar near "help"?
> 
>     2. May you please add the same section as "over last 30 days", but "all time"? (though I do not actually insist if it's difficult or you don't want for some other reason)

1. I think it should be there. Changing it has no purpose and logic.
2. Stats had been implemented as saving user's actions in the database. Storing too many of them will need a lot of memory. And any optimizations here are rather difficult to implement, it does not worth it. Big numbers could say nothing.

**Comment by zuevval** [comment]
> no purpose
On small screens buttons become too narrow, it’s the only reason. But maybe it’s OK, I’ll think more tomorrow

**Comment by zuevval** [comment]
> rather difficult to implement

Ok, understood, thank you

**Comment by zuevval** [comment]
Thanks for the fix. Now I could successfully update app (with new version code 9 and version tag 1.0.0 in Gradle config) via the wire on my tablet and phone over 1.0.2 **uploaded previously via debug cable (unsigned APK)** (though on the phone it crashed the first time, but afterwards it worked OK, lessons database is new and progress from 1.0.2 has been transferred).

But when I've generated a **signed APK** (also with code 9 and tag 1.0.0) (you may download it [here](https://drive.google.com/file/d/1aF3dAZ2vsSkzogTHObGebw0znb4OX8lb/view?usp=sharing)), I could not upgrade from 1.0.2 **downloaded from Play Market**.

   

Rather strange. Probably we shall first release beta version and see whether APK can be downloaded from Google Play.

**Comment by zuevval** [comment]
what about design: when I turn on "scan QR code" and "accessibility mode", the text displays improperly.

    

I want to shorten "scan QR-code" title. Which one is better?

**Comment by winter-yuki** [comment]
> what about design: when I turn on "scan QR code" and "accessibility mode", the text displays improperly.
> 
>  
> 
> I want to shorten "scan QR-code" title. Which one is better?
>  

The left one, I think. To be sure that everything will be ok on screens with different sizes.

**Comment by winter-yuki** [comment]
> Thanks for the fix. Now I could successfully update app (with new version code 9 and version tag 1.0.0 in Gradle config) via the wire on my tablet and phone over 1.0.2 **uploaded previously via debug cable (unsigned APK)** (though on the phone it crashed the first time, but afterwards it worked OK, lessons database is new and progress from 1.0.2 has been transferred).
> 
> But when I've generated a **signed APK** (also with code 9 and tag 1.0.0) (you may download it [here](https://drive.google.com/file/d/1aF3dAZ2vsSkzogTHObGebw0znb4OX8lb/view?usp=sharing)), I could not upgrade from 1.0.2 **downloaded from Play Market** (when I deleted the app from Play Market, installation succeeded).
> 
>  
> 
> Rather strange. Probably we shall first release beta or alpha version and see whether APK can be downloaded from Google Play over the older version.

Having a beta branch in google play will be great. But 1.0.2 should be released there previously to test migration to 1.1.0.

**Comment by zuevval** [comment]
I've uploaded a version for internal testing (it's even less public than alpha). In the evening, I hope, it will be published and I will check whether I can upgrade from 1.0.2.

@winter-yuki you may also join the test: https://play.google.com/apps/internaltest/4699080029412771895

**Comment by winter-yuki** [comment]
> I've uploaded a version for internal testing (it's even less public than alpha). In the evening, I hope, it will be published and I will check whether I can upgrade from 1.0.2.
> 
> @winter-yuki you may also join the test: https://play.google.com/apps/internaltest/4699080029412771895

Great! I'm confident about this branch more than about `dev`. So testing `dev` is not needed.

**Comment by winter-yuki** [comment]
Some important things are not clearly described in android docs, so experiments are required.

**Comment by winter-yuki** [comment]
Migrations run on the first DB request, and it can not affect the application upgrade. So the problem should be somewhere in packaging, I think.

**Comment by zuevval** [comment]
The update is published. I've successfully downloaded it over 1.0.2 on a tablet and a phone, everything works fine, the progress has been transmitted from the old version. 

I will check everything, maybe will make little changes in design, and then merge.

**Comment by zuevval** [comment]
@winter-yuki this request is almost ready to be merged, but may I please delay it a bit more and play around with layout?

This will take some time (presumably I'll finish it tomorrow around 13-00 PM), but maybe we will end up with a nicer design. I'll do it in a separate branch. <br>
I'm heading towards a state which is roughly like this :arrow_down: 


idea comes from here: https://github.com/kimbaudi/SimpleMovieQuiz

**Comment by winter-yuki** [comment]
Ok, I do not need something from here for browser

**Pull request merged**
