### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by winter-yuki**

### CODE REVIEW

**Comment by winter-yuki** [comment]
@zuevval did you test that Github testing fails with corrupted test cases?

**Comment by zuevval** [comment]
this request should be converted to draft, or please assign me and write how it is related to task (e. g. closes, or resolves some points)

**Comment by zuevval** [comment]
> @zuevval did you test that Github testing fails with corrupted test cases?

I am not sure I understand your question. Maybe we discuss during the evening meeting?

**Comment by zuevval** [comment]
I've opened pull request #249. Will wait for your resolution.

**Comment by winter-yuki** [comment]
@zuevval is it easy to add AVD tests and run CI on PRs? CI is useless in general without them.

**Comment by zuevval** [comment]
> @zuevval is it easy to add AVD tests and run CI on PRs? CI is useless in general without them.

1. I will try
1. yes, I will arrange it

**Comment by zuevval** [comment]
@winter-yuki I've added AVD tests to PR #249 and configured CI to be triggered only on PR opened or updated and on a push to master/dev

**Comment by zuevval** [comment]
And also I have added `kdoc` generation in request #249, but it's not deployed to any website, just uploaded to artifacts

**Comment by zuevval** [comment]
> @zuevval is it easy to add AVD tests and run CI on PRs? CI is useless in general without them.

@winter-yuki, by the way, there are a lot of ways to configure CI triggers. We may set it up to run or not run on PR opened, reopened, updated... https://docs.github.com/en/actions/reference/events-that-trigger-workflows

But I think that triggering workflow on PR opened/updated and on commits to dev/master is enough

**Comment by winter-yuki** [comment]
@zuevval feel free to merge it

**Comment by zuevval** [comment]
So you've resolved all `detekt` warnings the hard way, @winter-yuki. Well, do we need `detekt` at all then?

Can't you at least rename classes in DSL?

Note that it's a good practice to add a long and thorough explanation for each `SuppressWarning`, why it's absolutely necessary here. I do not think it's good to spend our time for it now... but can't you make a *slight effort* to fix at least *some* warnings?

**Comment by winter-yuki** [comment]
`detekt` has lots of inspections, I've suppressed some of them. 

I will not change class names because delegate names should start with lowercase.

**Comment by zuevval** [comment]
Apparently tests failed in a previous run due to some glitch which is not our fault. Now everything's OK

image

**Pull request merged**
