### PR TITLE
Feature/reflected dots

### LINKED ISSUE #223: Reflected braille dots
https://github.com/braille-systems/learn-braille/issues/221#issuecomment-664232669

### LINKED ISSUE #270: Checkable dots in hint mode
Dots are checkable after returning from help.

This code does not help:
```kotlin
if (viewModel.state == DotsChecker.State.HINT) {
    viewModel.expectedDots?.let {
        dotsState.display(it)
    }
}
```

The flip button makes them clickable too.

### LINKED ISSUE #271: HTML tags in ShowSymbol
in `dev` ShowSymbol steps containing `<br>` tag look like this:

image

This is the aftermath of the last refactoring.

Specifically, this happened after https://github.com/braille-systems/learn-braille/commit/40e454f3deed0f50fd782c33ca203701aa6a3241

TODO: fix

### PR DESCRIPTION
**Pull request by winter-yuki**
Closes #223 
Closes #270 
Closes #271 
Includes #267

### CODE REVIEW

**Comment by winter-yuki** [comment]
Implemented for `Practice` and `Browser`

**Comment by zuevval** [comment]
Brilliant!

But I still think that dots in the browser should be always in "reading mode" (123 on the left) by default regardless of settings, as I stated here: https://github.com/braille-systems/learn-braille/issues/223#issuecomment-679041931

**Comment by winter-yuki** [comment]
> Brilliant!
> 
> But I still think that dots in the browser should be always in "reading mode" (123 on the left) by default regardless of settings, as I stated here: [#223 (comment)](https://github.com/braille-systems/learn-braille/issues/223#issuecomment-679041931)

Okay, I just did not notice

**Comment by zuevval** [comment]
All of a sudden, an idea came to me. @winter-yuki is it difficult to produce a toast ("reading-mode"/"writing-mode") every time the columns are flipped?

**Comment by winter-yuki** [comment]
@zuevval см телегу

**Comment by winter-yuki** [comment]
> All of a sudden, an idea came to me. @winter-yuki is it difficult to produce a toast ("reading-mode"/"writing-mode") every time the columns are flipped?

No. Is this information needed in the same toast as the current deck name?

**Comment by zuevval** [comment]
> > All of a sudden, an idea came to me. @winter-yuki is it difficult to produce a toast ("reading-mode"/"writing-mode") every time the columns are flipped?
> 
> No. Is this information needed in the same toast as the current deck name?

Well, why not 😃

**Comment by winter-yuki** [comment]
I'm done here. There are some TODO's for @zuevval

**Review by zuevval — APPROVED** [review]
It was a bit tricky - to introduce columns inversion.

But it's done successfully at last. 🎆 

I've tried to check the UI very thoroughly and find it perfect.

**Pull request merged**
