### PR TITLE
#191 implement basic materials browser

### LINKED ISSUE #191: Add materials browser
Proposed by stakeholders in spring and considered worth implementing.

Possible implementation:

Transition from char to char - either via scrolling through the list or pushing side buttons

### PR DESCRIPTION
**Pull request by winter-yuki**
Closes #191

### CODE REVIEW

**Comment by winter-yuki** [comment]
Going to add decks list as in practice

**Comment by zuevval** [comment]
I've checked out. I find this implementation quite good even now.

**Comment by zuevval** [comment]
Ideas:
1. it might be useful to write dots numbers in the list, e. g. "Digit: 3 - dots 1, 4"
1. Maybe it's useful to extend messages when showing digits: "Digit 4 - number sign + letter D (dots 1, 4, 5)"

**Comment by winter-yuki** [comment]
Okay, choosing the deck does not do pretty much here.

1. done
2. Rather postpone it, not clear what letter language to choose is there will be any others later.
2. done

**Comment by zuevval** [comment]
1. Can't see it, have you pushed all your changes?
2. OK
3. Thank you! Will write it soon (in the evening)

May you please merge `dev` into this branch? I have an uneasy feeling that we again will face a problem of too many buttons in main menu

**Comment by winter-yuki** [comment]
Pushed for 1. item

**Comment by winter-yuki** [comment]
There are no help messages for new steps, the rest is good I think.

**Comment by zuevval** [comment]
Thanks! I feared that "Many Buttons In Main Menu" problem would rise again, but no, it's OK :slightly_smiling_face: 


I will write help texts by evening and then presumably will merge this and start a release procedure

**Comment by zuevval** [comment]
I would like to change the title from "materials" to "alphabet". I know it's not only alphabet there, but I think that "alphabet" will be understood better than "materials". @winter-yuki, what's your opinion?

**Comment by winter-yuki** [comment]
Maybe `SYMBOLS` will be better

**Comment by zuevval** [comment]
> Maybe `SYMBOLS` will be better

OK, did it

**Pull request merged**
